spring:
  application:
    name: calisthenics-backend-common
  datasource:
    url: jdbc:sqlserver://${CALISTHENICS_DB_HOST:localhost}:${CALISTHENICS_DB_PORT:1433};databaseName=${CALISTHENICS_DB_NAME:CALISTHENICS};encrypt=true;trustServerCertificate=true
    username: ${CALISTHENICS_DB_USERNAME:sa}
    password: ${CALISTHENICS_DB_PASSWORD:admin123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

calisthenics:
  db:
    bootstrap:
      enabled: true
