USE [CALISTHENICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_FN] [nvarchar](50) NOT NULL,
	[USER_LN] [nvarchar](50) NOT NULL,
	[USER_GENDER] [nvarchar](10) NOT NULL,
	[USER_AGE] [int] NOT NULL,
	[USER_EMAIL] [nvarchar](100) NOT NULL,
	[USER_MOBILE] [nvarchar](20) NOT NULL,
	[USER_EC_NAME] [nvarchar](100) NULL,
	[USER_EC_PHNO] [nvarchar](20) NULL,
	[USER_WEIGHT] [decimal](5, 2) NULL,
	[USER_HEIGHT] [decimal](5, 2) NULL,
	[USER_BMI]  AS (case when [USER_HEIGHT]>(0) then [USER_WEIGHT]/([USER_HEIGHT]*[USER_HEIGHT])  end) PERSISTED,
	[USER_IMAGE] [varbinary](max) NULL,
	[USER_ROLE] [nvarchar](20) NULL,
	[USER_JOIN_DATE] [date] NOT NULL,
	[USER_LAST_LOGIN] [datetime2](7) NULL,
	[USER_PASSWORD_HASH] [nvarchar](255) NULL,
	[STATUS] [nvarchar](20) NULL,
	[CREATED_AT] [datetime2](7) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_AT] [datetime2](7) NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_USER_EMAIL] UNIQUE NONCLUSTERED 
(
	[USER_EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER] ADD  DEFAULT ('Member') FOR [USER_ROLE]
GO

ALTER TABLE [dbo].[USER] ADD  DEFAULT ('Y') FOR [STATUS]
GO

ALTER TABLE [dbo].[USER] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[USER] ADD  DEFAULT (getdate()) FOR [MODIFIED_AT]
GO

ALTER TABLE [dbo].[USER]  WITH CHECK ADD CHECK  (([STATUS]='S' OR [STATUS]='N' OR [STATUS]='Y'))
GO

ALTER TABLE [dbo].[USER]  WITH CHECK ADD CHECK  (([USER_GENDER]='Other' OR [USER_GENDER]='Female' OR [USER_GENDER]='Male'))
GO

ALTER TABLE [dbo].[USER]  WITH CHECK ADD CHECK  (([USER_ROLE]='Member' OR [USER_ROLE]='Instructor' OR [USER_ROLE]='Admin'))
GO