USE [CALISTHENICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROGRESSIONS](
	[PROGRESSION_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROGRESSION_NAME] [nvarchar](100) NOT NULL,
	[PROGRESSION_DESCRIPTION] [nvarchar](max) NULL,
	[PROGRESSION_IMAGE] [varbinary](max) NULL,
	[COMPLETED] [bit] NULL,
	[STATUS] [nvarchar](20) NULL,
	[CREATED_AT] [datetime2](7) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_AT] [datetime2](7) NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_PROGRESSIONS] PRIMARY KEY CLUSTERED 
(
	[PROGRESSION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROGRESSIONS] ADD  DEFAULT ((0)) FOR [COMPLETED]
GO

ALTER TABLE [dbo].[PROGRESSIONS] ADD  DEFAULT ('Y') FOR [STATUS]
GO

ALTER TABLE [dbo].[PROGRESSIONS] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[PROGRESSIONS] ADD  DEFAULT (getdate()) FOR [MODIFIED_AT]
GO

ALTER TABLE [dbo].[PROGRESSIONS]  WITH CHECK ADD CHECK  (([STATUS]='N' OR [STATUS]='Y'))
GO


