USE [CALISTHENICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EXERCISES](
	[EXERCISE_ID] [int] IDENTITY(1,1) NOT NULL,
	[EXERCISE_NAME] [nvarchar](100) NOT NULL,
	[EXERCISE_DESCRIPTION] [nvarchar](max) NULL,
	[EXERCISE_DIFFICULTY] [nvarchar](20) NOT NULL,
	[EXERCISE_IMAGE] [varbinary](max) NULL,
	[STATUS] [nvarchar](20) NULL,
	[CREATED_AT] [datetime2](7) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_AT] [datetime2](7) NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_EXERCISES] PRIMARY KEY CLUSTERED 
(
	[EXERCISE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EXERCISES] ADD  DEFAULT ('Y') FOR [STATUS]
GO

ALTER TABLE [dbo].[EXERCISES] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[EXERCISES] ADD  DEFAULT (getdate()) FOR [MODIFIED_AT]
GO

ALTER TABLE [dbo].[EXERCISES]  WITH CHECK ADD CHECK  (([EXERCISE_DIFFICULTY]='Expert' OR [EXERCISE_DIFFICULTY]='Advanced' OR [EXERCISE_DIFFICULTY]='Intermediate' OR [EXERCISE_DIFFICULTY]='Beginner'))
GO

ALTER TABLE [dbo].[EXERCISES]  WITH CHECK ADD CHECK  (([STATUS]='N' OR [STATUS]='Y'))
GO


