USE [CALISTHENICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLASSES](
	[CLASS_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLASS_NAME] [nvarchar](100) NOT NULL,
	[CLASS_DESCRIPTION] [nvarchar](max) NULL,
	[CLASS_START_TIME] [time](7) NOT NULL,
	[CLASS_END_TIME] [time](7) NOT NULL,
	[CLASS_DURATION]  AS (datediff(minute,[CLASS_START_TIME],[CLASS_END_TIME])) PERSISTED,
	[CLASS_DATE] [date] NOT NULL,
	[CLASS_DAY] [nvarchar](10) NOT NULL,
	[CLASS_IMAGE] [varbinary](max) NULL,
	[CLASS_LOCATION] [nvarchar](100) NOT NULL,
	[CLASS_PRICE] [decimal](10, 2) NULL,
	[STATUS] [nvarchar](20) NULL,
	[CREATED_AT] [datetime2](7) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_AT] [datetime2](7) NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_CLASSES] PRIMARY KEY CLUSTERED 
(
	[CLASS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLASSES] ADD  DEFAULT ((0.00)) FOR [CLASS_PRICE]
GO

ALTER TABLE [dbo].[CLASSES] ADD  DEFAULT ('Y') FOR [STATUS]
GO

ALTER TABLE [dbo].[CLASSES] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[CLASSES] ADD  DEFAULT (getdate()) FOR [MODIFIED_AT]
GO

ALTER TABLE [dbo].[CLASSES]  WITH CHECK ADD CHECK  (([CLASS_DAY]='Sunday' OR [CLASS_DAY]='Saturday' OR [CLASS_DAY]='Friday' OR [CLASS_DAY]='Thursday' OR [CLASS_DAY]='Wednesday' OR [CLASS_DAY]='Tuesday' OR [CLASS_DAY]='Monday'))
GO

ALTER TABLE [dbo].[CLASSES]  WITH CHECK ADD CHECK  (([STATUS]='C' OR [STATUS]='N' OR [STATUS]='Y'))
GO


