USE [CALISTHENICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER_PROGRESSION](
	[USER_PROGRESSION_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[PROGRESSION_ID] [int] NOT NULL,
	[CURRENT_LEVEL] [int] NULL,
	[STARTED_DATE] [date] NOT NULL,
	[COMPLETED_DATE] [date] NULL,
	[STATUS] [nvarchar](20) NULL,
	[CREATED_AT] [datetime2](7) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_AT] [datetime2](7) NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_USER_PROGRESSION] PRIMARY KEY CLUSTERED 
(
	[USER_PROGRESSION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER_PROGRESSION] ADD  DEFAULT ((1)) FOR [CURRENT_LEVEL]
GO

ALTER TABLE [dbo].[USER_PROGRESSION] ADD  DEFAULT ('In Progress') FOR [STATUS]
GO

ALTER TABLE [dbo].[USER_PROGRESSION] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[USER_PROGRESSION] ADD  DEFAULT (getdate()) FOR [MODIFIED_AT]
GO

ALTER TABLE [dbo].[USER_PROGRESSION]  WITH CHECK ADD  CONSTRAINT [FK_USER_PROGRESSION_PROGRESSION] FOREIGN KEY([PROGRESSION_ID])
REFERENCES [dbo].[PROGRESSIONS] ([PROGRESSION_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[USER_PROGRESSION] CHECK CONSTRAINT [FK_USER_PROGRESSION_PROGRESSION]
GO

ALTER TABLE [dbo].[USER_PROGRESSION]  WITH CHECK ADD  CONSTRAINT [FK_USER_PROGRESSION_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([USER_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[USER_PROGRESSION] CHECK CONSTRAINT [FK_USER_PROGRESSION_USER]
GO

ALTER TABLE [dbo].[USER_PROGRESSION]  WITH CHECK ADD CHECK  (([STATUS]='Paused' OR [STATUS]='Completed' OR [STATUS]='In Progress'))
GO


