USE [CALISTHENICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EXERCISE_PROGRESSION](
	[EXERCISE_PROGRESSION_ID] [int] IDENTITY(1,1) NOT NULL,
	[EXERCISE_ID] [int] NOT NULL,
	[PROGRESSION_ID] [int] NOT NULL,
	[SEQUENCE_ORDER] [int] NOT NULL,
	[STATUS] [nvarchar](20) NULL,
	[CREATED_AT] [datetime2](7) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_AT] [datetime2](7) NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_EXERCISE_PROGRESSION] PRIMARY KEY CLUSTERED 
(
	[EXERCISE_PROGRESSION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EXERCISE_PROGRESSION] ADD  DEFAULT ('Y') FOR [STATUS]
GO

ALTER TABLE [dbo].[EXERCISE_PROGRESSION] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[EXERCISE_PROGRESSION] ADD  DEFAULT (getdate()) FOR [MODIFIED_AT]
GO

ALTER TABLE [dbo].[EXERCISE_PROGRESSION]  WITH CHECK ADD  CONSTRAINT [FK_EXERCISE_PROGRESSION_EXERCISE] FOREIGN KEY([EXERCISE_ID])
REFERENCES [dbo].[EXERCISES] ([EXERCISE_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[EXERCISE_PROGRESSION] CHECK CONSTRAINT [FK_EXERCISE_PROGRESSION_EXERCISE]
GO

ALTER TABLE [dbo].[EXERCISE_PROGRESSION]  WITH CHECK ADD  CONSTRAINT [FK_EXERCISE_PROGRESSION_PROGRESSION] FOREIGN KEY([PROGRESSION_ID])
REFERENCES [dbo].[PROGRESSIONS] ([PROGRESSION_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[EXERCISE_PROGRESSION] CHECK CONSTRAINT [FK_EXERCISE_PROGRESSION_PROGRESSION]
GO

ALTER TABLE [dbo].[EXERCISE_PROGRESSION]  WITH CHECK ADD CHECK  (([STATUS]='N' OR [STATUS]='Y'))
GO


