USE [CALISTHENICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLASS_BOOKING](
	[CLASS_BOOKING_ID] [int] IDENTITY(1,1) NOT NULL,
	[BOOKING_STATUS] [nvarchar](20) NULL,
	[BOOKING_DATE] [datetime2](7) NULL,
	[USER_ID] [int] NOT NULL,
	[CLASS_ID] [int] NOT NULL,
 CONSTRAINT [PK_CLASS_BOOKING] PRIMARY KEY CLUSTERED 
(
	[CLASS_BOOKING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLASS_BOOKING] ADD  DEFAULT ('Pending') FOR [BOOKING_STATUS]
GO

ALTER TABLE [dbo].[CLASS_BOOKING] ADD  DEFAULT (getdate()) FOR [BOOKING_DATE]
GO

ALTER TABLE [dbo].[CLASS_BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_CLASS_BOOKING_CLASS] FOREIGN KEY([CLASS_ID])
REFERENCES [dbo].[CLASSES] ([CLASS_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CLASS_BOOKING] CHECK CONSTRAINT [FK_CLASS_BOOKING_CLASS]
GO

ALTER TABLE [dbo].[CLASS_BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_CLASS_BOOKING_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([USER_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CLASS_BOOKING] CHECK CONSTRAINT [FK_CLASS_BOOKING_USER]
GO

ALTER TABLE [dbo].[CLASS_BOOKING]  WITH CHECK ADD CHECK  (([BOOKING_STATUS]='Completed' OR [BOOKING_STATUS]='Cancelled' OR [BOOKING_STATUS]='Confirmed' OR [BOOKING_STATUS]='Pending'))
GO


