USE [CALISTHENICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAYMENTS](
	[PAYMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[CLASS_ID] [int] NOT NULL,
	[AMOUNT] [decimal](10, 2) NOT NULL,
	[PAYMENT_METHOD] [nvarchar](20) NOT NULL,
	[PAYMENT_STATUS] [nvarchar](20) NULL,
	[PAYMENT_DATE] [datetime2](7) NULL,
	[TRANSACTION_ID] [nvarchar](100) NULL,
	[CREATED_AT] [datetime2](7) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_AT] [datetime2](7) NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_PAYMENTS] PRIMARY KEY CLUSTERED 
(
	[PAYMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PAYMENTS] ADD  DEFAULT ('Pending') FOR [PAYMENT_STATUS]
GO

ALTER TABLE [dbo].[PAYMENTS] ADD  DEFAULT (getdate()) FOR [PAYMENT_DATE]
GO

ALTER TABLE [dbo].[PAYMENTS] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[PAYMENTS] ADD  DEFAULT (getdate()) FOR [MODIFIED_AT]
GO

ALTER TABLE [dbo].[PAYMENTS]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENTS_CLASS] FOREIGN KEY([CLASS_ID])
REFERENCES [dbo].[CLASSES] ([CLASS_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PAYMENTS] CHECK CONSTRAINT [FK_PAYMENTS_CLASS]
GO

ALTER TABLE [dbo].[PAYMENTS]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENTS_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([USER_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PAYMENTS] CHECK CONSTRAINT [FK_PAYMENTS_USER]
GO

ALTER TABLE [dbo].[PAYMENTS]  WITH CHECK ADD CHECK  (([PAYMENT_METHOD]='Digital Wallet' OR [PAYMENT_METHOD]='Bank Transfer' OR [PAYMENT_METHOD]='Debit Card' OR [PAYMENT_METHOD]='Credit Card' OR [PAYMENT_METHOD]='Cash'))
GO

ALTER TABLE [dbo].[PAYMENTS]  WITH CHECK ADD CHECK  (([PAYMENT_STATUS]='Refunded' OR [PAYMENT_STATUS]='Failed' OR [PAYMENT_STATUS]='Completed' OR [PAYMENT_STATUS]='Pending'))
GO


